remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme # Required to use the remote theme
  - jekyll-feed
title: Having fun...
author: 
   name: Rodrigo Cuevas A.
description: A simple blog, for simple stories.
minima:
   skin: auto
   date_format: "%d-%m-%Y"
   social_links: 
      - title: Github Page
        icon: github
        url: "https://github.com/rcuevasa"
