# not the default thene, instead remote
theme: minima
#remote_theme: jekyll/minima
#plugins:
#  - jekyll-remote-theme # Required to use the remote theme
#minima:
#  skin: auto
title: Having fun...
author: 
   name: Rodrigo Cuevas A.
description: A simple blog, for simple stories.
minima:
   skin: auto
date_format: "%d-%b-%Y"
social_links: 
   - title: Github Page
     icon: github
     url: "https://github.com/rcuevasa"
